sending_app/notions/urls.py
from django.urls import path

from . import views

app_name = "notions"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "clients/form/",
        views.ClientCreateView.as_view(),
        name="clients_create_form",
    ),
    path(
        "clients/form/<int:pk>/edit/",
        views.ClientUpdateView.as_view(),
        name="clients_update_form",
    ),
    path(
        "clients/form/<int:pk>/delete/",
        views.ClientDeleteView.as_view(),
        name="clients_delete_form",
    ),
    path(
        "tasks/form/",
        views.NotionCreateTaskView.as_view(),
        name="tasks_create_form",
    ),
    path(
        "tasks/form/<int:pk>/edit/",
        views.NotionUpdateView.as_view(),
        name="tasks_update_form",
    ),
    path(
        "tasks/form/<int:pk>/delete/",
        views.NotionDeleteView.as_view(),
        name="tasks_delete_form",
    ),
    path("send/<int:pk>/", views.send_messages, name="send_messages"),
    path("tasks/<int:pk>/", views.notification_page, name="notification_page"),
]

sending_app/sending_app/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("notions.urls", "notions"), namespace="notions")),
]

sending_app/notions/models.py
from django.db import models
from django.core.validators import RegexValidator


class Tag(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class NotionTask(models.Model):
    start_pub_date = models.DateTimeField(
        "Дата и время запуска рассылки", blank=True
    )
    end_pub_date = models.DateTimeField(
        "Дата и время окончания рассылки", blank=True
    )
    text = models.TextField(verbose_name="Текст сообщения", blank=True)
    tags = models.ManyToManyField(Tag, related_name="notion_task")

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"


class Client(models.Model):
    phone_regex = RegexValidator(
        regex=r"^(7)?[0-9]{10}$",  # "/^([7]?[0-9]{3,11})*$/i;",
        message="Номер телефона должен быть в формате 7XXXXXXXXXX (X - цифра от 0 до 9)",
    )
    phone_number = models.CharField(
        validators=[phone_regex], max_length=11, blank=False
    )
    operator_code_regex = RegexValidator(
        regex=r"^[0-9]{1,5}$",
        message="Код мобильного оператора введен не верно. Должны быть только цифры",
    )
    operator_code = models.CharField(
        validators=[operator_code_regex], max_length=5, blank=False
    )
    tags = models.ManyToManyField(Tag, related_name="client")
    time_zone = models.SmallIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.phone_number

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Messages(models.Model):
    create_date = models.DateTimeField(
        "Дата создания (отправки)", auto_now_add=True, db_index=True
    )
    status = models.BooleanField(default=False)
    notion = models.ForeignKey(
        NotionTask,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="message",
    )
    client = models.ForeignKey(
        Client,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="message",
    )

    def __str__(self):
        return "messages type"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

sending_app/notions/forms.py
from django import forms
from .models import NotionTask, Client
from django.utils import timezone


class NotionTaskForm(forms.ModelForm):
    start_pub_date = forms.SplitDateTimeField(
        initial=timezone.now(),
    )
    end_pub_date = forms.SplitDateTimeField(initial=timezone.now())

    class Meta:
        model = NotionTask
        fields = "__all__"


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"

sending_app/notions/views.py
import os
import requests

from django.utils import timezone
from dotenv import load_dotenv
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import NotionTaskForm, ClientForm
from .models import NotionTask, Client, Messages

load_dotenv()
AUTH_TOKEN = os.getenv("AUTH_TOKEN")
URL = "https://probe.fbrq.cloud/v1/send/"


def index(request):
    notions = NotionTask.objects.order_by("-start_pub_date")[:10]
    clients = Client.objects.order_by(("-pk")[:10])
    now = timezone.now()
    context = {"notions": notions, "clients": clients, "now": now}
    return render(request, "notions/list.html", context)


def notification_page(request, pk):
    notion = get_object_or_404(NotionTask, pk=pk)
    context = {"notion": notion}
    return render(request, "notions/page.html", context)


def send_messages(request, pk):
    header = {"Authorization": "Bearer " + AUTH_TOKEN}
    notion = get_object_or_404(NotionTask, pk=pk)
    if notion.start_pub_date < timezone.now() < notion.end_pub_date:
        tags = notion.tags.all()
        clients = Client.objects.filter(tags__in=tags)

        def sending(client):
            number = int(client.operator_code + client.phone_number)
            data = {"id": client.id, "phone": number, "text": notion.text}
            response = requests.post(
                URL + str(data["id"]), json=data, headers=header
            )
            if response.status_code == 200:
                status = True
            Messages.objects.get_or_create(
                status=status,
                notion=notion,
                client=client,
            )

        for client in clients:
            try:
                sending(client)
            except requests.exceptions.HTTPError as errh:
                print("Http Error:", errh)
            except requests.exceptions.ConnectionError as errc:
                print("Error Connecting:", errc)
            except requests.exceptions.Timeout as errt:
                print("Timeout Error:", errt)
            except requests.exceptions.RequestException as err:
                print("OOps: Something Else", err)

    else:
        print("Time is over")
    return redirect("notions:index")


class NotionCreateTaskView(CreateView):
    form_class = NotionTaskForm
    template_name = "notions/form.html"
    success_url = "/"


class NotionUpdateView(UpdateView):
    model = NotionTask
    form_class = NotionTaskForm
    template_name = "notions/form_update.html"
    success_url = "/"


class NotionDeleteView(DeleteView):
    model = NotionTask
    template_name = "notions/form_delete.html"
    success_url = "/"


class ClientCreateView(CreateView):
    form_class = ClientForm
    template_name = "clients/form.html"
    success_url = "/"


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "clients/form_update.html"
    success_url = "/"


class ClientDeleteView(DeleteView):
    model = Client
    template_name = "clients/form_delete.html"
    success_url = "/"

sending_app/templates/clients/form.html
<h2>Client Form</h2>
<form method="post" action="{% url 'notions:clients_create_form' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form> 

sending_app/templates/clients/form_delete.html
<h2>Client Form</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>
  

sending_app/templates/clients/form_update.html
<h2>Client Form</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form> 

sending_app/templates/notions/form.html
<h2>Notification Form</h2>
<form method="post" action="{% url 'notions:tasks_create_form' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form> 

sending_app/templates/notions/form_delete.html
<h2>Notification Form</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>
  

sending_app/templates/notions/form_update.html
<h2>Notification Form</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
  </form> 

sending_app/templates/notions/index.html
{% load static %} 

{% block header %}{% endblock %}
{% block content %} 
<p><a href="/tasks/form/">Create Notification</a></p>
<p><a href="/tasks/form/">Add Client</a></p>
{% endblock %} 


 

sending_app/templates/notions/list.html
{% extends 'notions/index.html' %}
{% load filters %}

{% block content %} 
<h2>Notification Tasks</h2>
<p><a href="/tasks/form/">Create Notification</a></p>
  <table style="width:100%">
    <tbody>
    <tr>
    <td>id</td>
    <td>Edit / Remove</td>
    <td>Send</td>
    <td>Start date</td>
    <td>End date</td>
    <td>Notification text</td>
    <td>Tags</td>
    <td>Statistics</td>
    </tr>
    {% for notion in notions %}
    <tr>
    <td> <p> <a href="{% url 'notions:notification_page' notion.id %}">{{ notion.id }}</a> </p> </td>
    <td> 
      <p>
        <a href="{% url 'notions:tasks_update_form' notion.id %}">Edit</a> / 
        <a href="{% url 'notions:tasks_delete_form' notion.id %}">Remove</a>
      </p>
    </td>
    <td> 
      <p>
        {% if notion.start_pub_date < now and now < notion.end_pub_date %}
          <a href="{% url 'notions:send_messages' notion.id %}">Send</a>
        {% else %}
            Expired
        {% endif %}
      </p>
    </td>
    <td> <p>{{ notion.start_pub_date }}</p> </td>
    <td> <p>{{ notion.end_pub_date }}</p> </td>
    <td> <p>{{ notion.text }}</p> </td>
    <td> <p>
      {% for tag in notion.tags.all %}
      {{ tag.name }}
      {% endfor %}
    </p> 
    </td>
    <td> 
      <p>
        Total sent: {{ notion.message.count}} <br>
        Success: {{ notion.message|count_true }}<br>
        False: {{ notion.message|count_false }} 
      <p>
    </td>
    </tr>
    {% endfor %} 
    </tbody>
</table>

<h2>Clients List</h2>
<p><a href="/clients/form/">Add Client</a></p>
<table style="width:100%">
  <tbody>
  <tr>
  <td>id</td>
  <td>Edit / Remove</td>
  <td>Operator Code</td>
  <td>Phone Number</td>
  <td>Time Zome</td>
  <td>Tags</td>
  </tr>
  {% for client in clients %}
  <tr>
  <td> <p>{{ client.id }}</p> </td>
  <td> 
    <p>
      <a href="{% url 'notions:clients_update_form' client.id %}">Edit</a> / 
      <a href="{% url 'notions:clients_delete_form' client.id %}">Remove</a>
    </p>
  </td>
  <td> <p>{{ client.operator_code }}</p> </td>
  <td> <p>{{ client.phone_number }}</p> </td>
  <td> <p>{{ client.time_zone }}</p> </td>
  <td> <p>
    {% for tag in client.tags.all %}
    {{ tag.name }}
    {% endfor %}
  </p> 
  </td>
  </tr>
  {% endfor %} 
  </tbody>
{% endblock %} 

sending_app/templates/notions/page.html
{% extends 'notions/index.html' %}
{% load filters %}

{% block content %} 
<h2>Notification Task</h2>
<p><a href="/tasks/form/">Create Notification</a></p>
  <table style="width:100%">
    <tbody>
    <tr>
    <td>id</td>
    <td>Start date</td>
    <td>End date</td>
    <td>Notification text</td>
    <td>Tags</td>
    </tr>
    <tr>
    <td> <p>{{ notion.id }}</p> </td>
    <td> <p>{{ notion.start_pub_date }}</p> </td>
    <td> <p>{{ notion.end_pub_date }}</p> </td>
    <td> <p>{{ notion.text }}</p> </td>
    <td> <p>
      {% for tag in notion.tags.all %}
      {{ tag.name }}
      {% endfor %}
    </p> 
    </td>
    </tr>
    </tbody>
</table>

<p>
  Total sent: {{ notion.message.count}} <br>
  Success: {{ notion.message|count_true }}<br>
  False: {{ notion.message|count_false }} 
<p>


  <h2>Messages </h2>
  <table style="width:100%">
    <tbody>
    <tr>
    <td>id</td>
    <td>Sent date</td>
    <td>Status</td>
    <td>Client phone</td>
    </tr>
    {% for message in notion.message.all %}
    <tr>
    <td> <p>{{ message.id}}</p> </td>
    <td> <p>{{ message.create_date }}</p></td>
    <td> <p>{{ message.status }}</p></td>
    <td> <p>{{ message.client }}</p></td> 
    </tr>
    {% endfor %} 
    </tbody>

{% endblock %} 